baseURL = "https://simplemath.io/"
languageCode = "en-us"
title = "Demystifying Math"
theme = "tongass"
author = "Forest Kobayashi"
copyright = "&copy; 2017. All rights reserved."
paginate = 10
canonifyurls = true

[params]
	# Shown in the home page
	subtitle = "An attempt to make mathematics more accessible"
	brand = "Menu"
	googleAnalytics = "UA-99652813-1"
	disqus = "Forest Kobayashi"
	# CSS name for highlight.js
	highlightjs = "androidstudio"
	dateFormat = "02 Jan 2006, 15:04"

[menu]
	[[menu.main]]
    	name = "Home"
    	weight = -1
    	identifier = "home"
    	url = "/home/"
	[[menu.main]]
    	name = "About"
    	weight = 3
    	identifier = "about"
    	url = "/about/"
	[[menu.main]]
		name = "Math"
		weight = 2 
		identifier = "math"
		url = "/math/"
		[[menu.main]]
			name = "Calculus"
			parent = "math"
			weight = 1
			identifier = "calculus"
			url = "/math/calculus/"
		[[menu.main]]
			name = "Discrete"
			parent = "math"
			weight = 2
			identifier = "discrete"
			url = "/math/discrete/"
	[[menu.main]]
		name = "Physics"
		weight = 2 
		identifier = "physics"
		url = "/physics/"
		[[menu.main]]
			name = "Mechanics"
			parent = "physics"
			weight = 1
			identifier = "mechanics"
			url = "/physics/mechanics/"
		[[menu.main]]
			name = "Gravitation"
			parent = "physics"
			weight = 2
			identifier = "gravitation"
			url = "/physics/gravitation/"
		[[menu.main]]
			name = "E&M"
			parent = "physics"
			weight = 2
			identifier = "e&m"
			url = "/physics/E&M/"

[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  youtube = "coldsoup49"
  facebook = "forsoisatorso"
  github = "redpanda1234"
  stackoverflow = "*"
  linkedin = "*"